name: helpis_cli
description: This CLI provides various commands to help with Dart/Flutter development.
repository: https://github.com/helpisdev/helpis_cli
version: 0.2.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  dart_console: ^1.1.2
  dcli: ^2.2.2
  path: ^1.8.3
  pubspec_yaml: ^3.1.0
  universal_io: ^2.2.1
  xml: ^6.3.0

dependency_overrides:
  collection: ^1.17.2
  matcher: ^0.12.16
  scope: ^4.0.0
  win32: ^5.0.1

executables:
  helpis:
dev_dependencies:
  melos: ^3.1.0
