name: helpis_cli
description: This CLI provides various commands to help with Dart/Flutter development.
repository: https://github.com/helpisdev/helpis_cli
version: 0.2.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  collection: ^1.17.2
  dart_console: ^1.2.0
  dcli: ^3.0.3
  path: ^1.8.3
  pubspec_yaml: ^3.1.0
  universal_io: ^2.2.2
  xml: ^6.3.0

dev_dependencies:
  melos: ^3.1.0

dependency_overrides:
  collection: ^1.17.2
  dcli: ^3.0.3
  file: ^7.0.0
  http: ^1.1.0
  matcher: ^0.12.16
  pubspec2: ^3.0.0
  scope: ^4.0.1
  win32: ^5.0.5

executables:
  helpis:
