Map<String, dynamic> mason({
  required final bool isDart,
  required final bool fluttergen,
  required final List<dynamic> flavors,
  required final String name,
  required final String author,
  required final String username,
  required final String desc,
  required final String version,
  required final String repo,
  required final String homepage,
  required final String org,
  required final String ide,
  required final List<dynamic> platforms,
  required final String revolt,
}) =>
    <String, dynamic>{
      'dart': isDart,
      'fluttergen': fluttergen,
      'hasFlavors': flavors.isNotEmpty,
      'flavors': flavors,
      'name': name,
      'author': author,
      'authorUsername': username,
      'description': desc,
      'version': version,
      'repository': repo,
      'homepage': homepage,
      'org': org,
      'IDE': ide,
      'platforms': platforms,
      'revolt': revolt,
    };
